version: "3"
services:
  db:
    image: postgres:alpine
    environment:
    - POSTGRES_PASSWORD=pg123456
    ports:
    - 5432:5432
    volumes:
    - ./db:/docker-entrypoint-initdb.d:ro
    - data:/var/lib/postgresql/data
volumes:
  data: