version: "3"
services:
  db:
    image: postgres:alpine
    container_name: esb-db
    environment:
    - POSTGRES_PASSWORD=pg123456
    ports:
    - 5432:5432
    volumes:
    - ./db:/docker-entrypoint-initdb.d:ro
    - data:/var/lib/postgresql/data
    command: postgres -c max_connections=1000
  manager:
    image: wso2esb:5.0.0
    container_name: esb-manager
    volumes:
    - ./config/manager/master-datasources.xml:/opt/wso2esb-5.0.0/repository/conf/datasources/master-datasources.xml:ro
    - ./config/manager/user-mgt.xml:/opt/wso2esb-5.0.0/repository/conf/user-mgt.xml:ro
    - ./config/manager/registry.xml:/opt/wso2esb-5.0.0/repository/conf/registry.xml:ro
    - ./config/manager/axis2.xml:/opt/wso2esb-5.0.0/repository/conf/axis2/axis2.xml:ro
    - ./config/manager/jndi.properties:/opt/wso2esb-5.0.0/repository/conf/jndi.properties:ro
    entrypoint: /opt/wso2esb-5.0.0/bin/wso2server.sh
    depends_on:
    - db
  worker1:
    image: wso2esb:5.0.0
    container_name: esb-worker1
    volumes:
    - ./config/worker/master-datasources.xml:/opt/wso2esb-5.0.0/repository/conf/datasources/master-datasources.xml:ro
    - ./config/worker/user-mgt.xml:/opt/wso2esb-5.0.0/repository/conf/user-mgt.xml:ro
    - ./config/worker/registry.xml:/opt/wso2esb-5.0.0/repository/conf/registry.xml:ro
    - ./config/worker/1/axis2.xml:/opt/wso2esb-5.0.0/repository/conf/axis2/axis2.xml:ro
    - ./config/worker/jndi.properties:/opt/wso2esb-5.0.0/repository/conf/jndi.properties:ro
    entrypoint: /opt/wso2esb-5.0.0/bin/wso2server.sh -DworkerNode=true
    depends_on:
    - manager
  worker2:
    image: wso2esb:5.0.0
    container_name: esb-worker2
    volumes:
    - ./config/worker/master-datasources.xml:/opt/wso2esb-5.0.0/repository/conf/datasources/master-datasources.xml:ro
    - ./config/worker/user-mgt.xml:/opt/wso2esb-5.0.0/repository/conf/user-mgt.xml:ro
    - ./config/worker/registry.xml:/opt/wso2esb-5.0.0/repository/conf/registry.xml:ro
    - ./config/worker/2/axis2.xml:/opt/wso2esb-5.0.0/repository/conf/axis2/axis2.xml:ro
    - ./config/worker/jndi.properties:/opt/wso2esb-5.0.0/repository/conf/jndi.properties:ro
    entrypoint: /opt/wso2esb-5.0.0/bin/wso2server.sh -DworkerNode=true
    depends_on:
    - manager
  nginx:
    image: nginx:alpine
    container_name: esb-lb
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./config/nginx:/etc/nginx/conf.d:ro
    - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
    - worker1
    - worker2
volumes:
  data: