filebeat.prospectors:
- input_type: log
  paths:
  - /opt/jboss/jboss-eap-6.4/standalone/log/meta-search.log
  multiline:
    pattern: '^(\x1B\[[0-9]+m)*\[[0-9]{2}/[0-9]{2}/[0-9]{4}'
    negate: true
    match: after
- input_type: log
  paths:
  - /opt/jboss/jboss-eap-6.4/standalone/log/*.log
  exclude_files: ['meta-search\.log$']
  multiline:
    pattern: '^\[[0-9]{2}/[0-9]{2}/[0-9]{4}'
    negate: true
    match: after
name: "meta"
output.logstash:
  hosts: ["logstash:5044"]
