version: "3"

services:

  db:
    image: postgres:alpine
    volumes:
    - db:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

  qube:
    image: sonarqube:alpine
    volumes:
    - data:/opt/sonarqube/data
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    ports:
    - 9000:9000
    depends_on:
    - db

volumes:
  db:
  data:
