GRANT ALL PRIVILEGES ON DATABASE wso2_user_db TO esb;
GRANT ALL PRIVILEGES ON DATABASE registry_db TO esb;
GRANT ALL PRIVILEGES ON DATABASE registry_local1 TO esb;
GRANT ALL PRIVILEGES ON DATABASE registry_local2 TO esb;
