\c wso2_user_db
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO esb;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO esb;

\c registry_db
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO esb;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO esb;

\c registry_local1
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO esb;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO esb;

\c registry_local2
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO esb;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO esb;