filebeat.prospectors:
- input_type: log
  paths:
  - /elasticsearch-1.7.1/logs/*.log
  multiline:
    pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
name: "elasticsearch"
output.logstash:
  hosts: ["ls_harvester:5044"]
