version: "3"
services:
    mysql:
        image: mysql
        volumes:
        - data:/var/lib/mysql
        networks:
        - nw
        ports: 
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=rOot123.,
    hazelcast:
        build: ./hazelcast
        networks:
        - nw
    elasticsearch:
        build: ./elasticsearch
        networks:
        - nw
        ports:
        - 9200:9200
    jboss:
        build: ./jboss
        networks:
        - nw
        ports:
        - 8080:8080
        - 9990:9990
        - 9999:9999
volumes: 
    data:
networks: 
    nw:
