version: "3"
services:
    mysql:
        image: mysql:5
        volumes:
        - data:/var/lib/mysql
        # - ./sql:/docker-entrypoint-initdb.d JUST FOR INITIALIZATION
        networks:
        - nw
        ports: 
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=rOot123.,
    hazelcast:
        build: ./hazelcast
        networks:
        - nw
    elasticsearch:
        build: ./elasticsearch
        networks:
        - nw
        ports:
        - 9200:9200
    meta:
        build: ./meta
        #command: bash -c "/etc/init.d/filebeat start && /opt/jboss/bin/standalone.sh"
        volumes:
        - files:/opt/jboss/data
        - ./deployments/meta:/opt/jboss/jboss-eap-6.4/standalone/deployments
        networks:
        - nw
        ports:
        - 8080:8080
        - 9990:9990
        depends_on:
        - mysql
        - elasticsearch
        - hazelcast
    hub:
        build: ./hub
        #command: bash -c "/etc/init.d/filebeat start && /opt/jboss/bin/standalone.sh"
        volumes:
        - ./deployments/hub:/opt/jboss/jboss-eap-6.4/standalone/deployments
        networks:
        - nw
        ports:
        - 8081:8080
        - 9991:9990
        depends_on:
        - meta
    downloader:
        build: ./downloader
        volumes:
        - files:/data
        networks:
        - nw
    logstash:
        build: ./logstash
        networks:
        - nw
        depends_on:
        - meta
        - hub
    elastic:
        image: elasticsearch:alpine
        networks:
        - nw
        ports:
        - 9201:9200
        depends_on:
        - logstash
    kibana:
        image: kibana
        environment:
        - ELASTICSEARCH_URL=http://elastic:9200
        networks:
        - nw
        ports:
        - 5601:5601
        depends_on:
        - elastic
volumes: 
    data:
    files:
networks: 
    nw:
