version: "3"
services:
    mysql:
        image: mysql:5
        volumes:
        - data:/var/lib/mysql
        networks:
        - nw
        ports: 
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=rOot123.,
    hazelcast:
        build: ./hazelcast
        networks:
        - nw
        logging:
          driver: gelf
          options:
            gelf-address: "udp://localhost:12201"
        depends_on:
        - logstash
    elasticsearch:
        build: ./elasticsearch
        networks:
        - nw
        depends_on:
        - logstash
    meta:
        build: ./meta
        volumes:
        - files:/home/jboss/data
        - ./deployments/meta:/opt/jboss/jboss-eap-6.4/standalone/deployments
        networks:
        - nw
        ports:
        - 8080:8080
        - 9990:9990
        depends_on:
        - mysql
        - elasticsearch
        - hazelcast
        - logstash
    hub:
        build: ./hub
        volumes:
        - ./deployments/hub:/opt/jboss/jboss-eap-6.4/standalone/deployments
        networks:
        - nw
        ports:
        - 8081:8080
        - 9991:9990
        depends_on:
        - meta
        - logstash
    downloader:
        build: ./downloader
        volumes:
        - files:/data
        networks:
        - nw
        depends_on:
        - meta
    logstash:
        build: ./logstash
        networks:
        - nw
        ports:
        - 12201:12201/udp
        depends_on:
        - elastic
    elastic:
        image: elasticsearch:alpine
        volumes:
        - logs:/usr/share/elasticsearch/data
        networks:
        - nw
    kibana:
        image: kibana
        environment:
        - ELASTICSEARCH_URL=http://elastic:9200
        networks:
        - nw
        ports:
        - 5601:5601
        depends_on:
        - elastic
volumes: 
    data:
    files:
    logs:
networks: 
    nw:
