version: '2'
services:
    master:
        image: elasticsearch:alpine
        container_name: elasticsearch_master
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        command: [
            -Ecluster.name=my_cluster, 
            -Enode.name=master_node, 
            -Ebootstrap.memory_lock=true,
            ]
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add: 
            - IPC_LOCK
        ports:
            - 9200:9200
        volumes_from: 
            - container:elastic-data
        networks:
            - net
    node:
        image: elasticsearch:alpine
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        command: [
            -Ecluster.name=my_cluster, 
            -Ebootstrap.memory_lock=true, 
            -Ediscovery.zen.ping.unicast.hosts=elasticsearch_master
            ]
        depends_on: 
            - master
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add: 
            - IPC_LOCK
        volumes_from: 
             - container:elastic-data
        networks:
            - net
networks:
    net:
        driver: bridge
