version: '2'
services:
    elastic1:
        image: elasticsearch:alpine
        container_name: elastic1
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        command: [
            -Ecluster.name=my_cluster, 
            -Enode.name=my_node1, 
            -Ebootstrap.memory_lock=true,
            -Ediscovery.zen.minimum_master_nodes=2
            ]
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add: 
            - IPC_LOCK
        ports:
            - 9200:9200
        networks:
            - es-net
    elastic2:
        image: elasticsearch:alpine
        container_name: elastic2
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        command: [
            -Ecluster.name=my_cluster, 
            -Enode.name=my_node2, 
            -Ebootstrap.memory_lock=true, 
            -Ediscovery.zen.minimum_master_nodes=2,
            -Ediscovery.zen.ping.unicast.hosts=elastic1
            ]
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g
        cap_add: 
            - IPC_LOCK
        ports:
            - 9201:9200
        networks:
            - es-net
networks:
    es-net:
        driver: bridge
