version: "3"
services:
  mysql:
    image: mysql:5
    networks:
    - nw
    ports: 
    - 3306:3306
    volumes:
    - data_mysql:/var/lib/mysql
    environment: 
    - MYSQL_ROOT_PASSWORD=rOot123.,
  wso2:
    image: wso2esb-feat-dss
    networks:
    - nw
    ports: 
    - 8280:8280
    - 9443:9443
    volumes:
    - ./datasources:/opt/wso2esb-5.0.0/repository/conf/datasources
    - ./lib:/opt/wso2esb-5.0.0/repository/components/lib
    - ./carbonapps:/opt/wso2esb-5.0.0/repository/deployment/server/carbonapps
    - ./dataservices:/opt/wso2esb-5.0.0/repository/deployment/server/dataservices
    depends_on: 
    - mysql
volumes: 
  data_mysql:
networks: 
  nw:
