# Login: elastic/changeme
version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
    - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    environment:
    - ELASTICSEARCH_URL=http://elastic:9200
    ports:
    - 5601:5601
    depends_on:
    - elastic