version: "3"
services:
    mssql:
        image: microsoft/mssql-server-linux
        volumes:
        - data:/var/opt/mssql/data
        environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=rOot123.,
        ports:
        - 1433:1433
volumes:
    data: