USE master;
IF EXISTS(SELECT 1 FROM sys.databases where name='CHESS') DROP DATABASE CHESS;

CREATE DATABASE CHESS;
USE CHESS;

CREATE TABLE GAMES (
	ID int IDENTITY(1,1) PRIMARY KEY,
	WHITE_OPPONENT varchar(50) NOT NULL,
	BLACK_OPPONENT varchar(50) NOT NULL
);

CREATE TABLE MOVES (
	IDGAME int NOT NULL,
	NUM int NOT NULL,
	MOVE_WHITE char(10) NOT NULL,
	MOVE_BLACK char(10),
	PRIMARY KEY (IDGAME, NUM)
);
ALTER TABLE MOVES ADD CONSTRAINT FK_MOVES_GAMES FOREIGN KEY (IDGAME) REFERENCES GAMES(ID);

INSERT INTO GAMES(WHITE_OPPONENT, BLACK_OPPONENT) VALUES('KARPOV', 'KASPAROV');
INSERT INTO GAMES(WHITE_OPPONENT, BLACK_OPPONENT) VALUES('FISHER', 'ALEKHINE');

INSERT INTO MOVES VALUES(1, 1,'e2-e4', 'c7-c5');
INSERT INTO MOVES VALUES(1, 2,'Ng1-f3', 'd7-d6');
INSERT INTO MOVES VALUES(2, 1,'d2-d4', 'd7-d5');
INSERT INTO MOVES VALUES(2, 2,'Nb1-c3', 'Ng8-f6');
